### ISSUE TITLE
Does not generate tiles, even with provided example SVG

### ISSUE THREAD

**Issue by Rayjax** [economia/svg-mapper#2]
Hi, I think I must have missed something in the setup process.
I installed pixman, cairo, node-canvas, and the npm module. I am not able to generate any tile from any svg. I tried all possible options, several files, without success. Here is an example (tried with and without sudo):

svg-mapper-master/example$ sudo svg-mapper ./example.svg -z 5-8
Generating metadata for ./example.svg
fs.js:584
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open './example//data.json'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    at /usr/local/lib/node_modules/svg-mapper/bin/cli.js:68:12
    at ChildProcess.exithandler (child_process.js:220:5)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:821:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:90:13)
andrea@t:~/Desktop/svg-mapper-master/example$ sudo svg-mapper ./example.svg -z 5-8
Directory already exists or is not creatable, skipping: ./example/
Starting tile generation. Using 4 cores to do 0 jobs.
All done, tiles are now in same directory as ./example.svg
andrea@t:~/Desktop/svg-mapper-master/example$ ls
big.png\*               generator.html*
big_dataContoured.png\* kraje.geojson*
example/               leaflet.html*
example.svg\*           output/
andrea@t:~/Desktop/svg-mapper-master/example$ cd example
andrea@t:~/Desktop/svg-mapper-master/example/example$ ls
--> empty

The first time I will try to convert a file, I would get the first error. All the following tries will give the second one. Always 0 jobs to do. Did I miss something ?

**Comment by bel3atar** [comment]
I confirm the problem.

**Comment by veproza** [comment]
Hi guys, thanks for reporting this and sorry for my long delay.

The error was caused by old jsdom's contextify, which was apparently running haywire. I updated the dependencies to newest versions of jsdom and jquery and pushed new **0.0.4** to npm. It should be working fine now, at least with the example svg :-)

If you run into any trouble, please do contact me, I'll try to be faster this time around.

**Comment by bel3atar** [comment]
@veproza I tried it on an SVG and it generated unwanted colourful striped on it.

**Comment by veproza** [comment]
@bel3atar Can you please post the SVG in question? I'll be honest, the tool is a stitched-together piece  of barely cooperating tools, but it always worked for me.

**Comment by bel3atar** [comment]
@veproza sent to jmeno.prijmeni@samizdat.cz
